# Generated by Django 4.2 on 2025-01-10 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='type',
            field=models.CharField(choices=[('E', 'Elèctrico'), ('T', 'Tierra'), ('P', 'Planta'), ('F', 'Fuego'), ('A', 'Agua'), ('L', 'Lagartija')], max_length=30),
        ),
    ]
