# Generated by Django 4.2 on 2025-01-10 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0002_alter_pokemon_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='type',
            field=models.CharField(choices=[('T', 'Tierra'), ('L', 'Lagartija'), ('P', 'Planta'), ('E', 'Elèctrico'), ('A', 'Agua'), ('F', 'Fuego')], max_length=30),
        ),
    ]
