# Generated by Django 4.2 on 2024-12-21 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0002_trainer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainer',
            name='level',
            field=models.IntegerField(default=1),
        ),
    ]
