# Generated by Django 4.2 on 2024-12-21 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0003_alter_trainer_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='type',
            field=models.CharField(choices=[('L', 'Lagartija'), ('P', 'Planta'), ('A', 'Agua'), ('F', 'Fuego'), ('E', 'Elèctrico'), ('T', 'Tierra')], max_length=30),
        ),
    ]
