# Generated by Django 4.2 on 2025-01-17 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0005_alter_pokemon_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainer',
            name='trainer_picture',
            field=models.ImageField(blank=True, null=True, upload_to='trainers_images'),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='type',
            field=models.CharField(choices=[('T', 'Tierra'), ('A', 'Agua'), ('F', 'Fuego'), ('L', 'Lagartija'), ('E', 'Elèctrico'), ('P', 'Planta')], max_length=30),
        ),
    ]
