# Generated by Django 4.2 on 2025-01-17 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0006_trainer_trainer_picture_alter_pokemon_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='type',
            field=models.CharField(choices=[('T', 'Tierra'), ('F', 'Fuego'), ('L', 'Lagartija'), ('A', 'Agua'), ('E', 'Elèctrico'), ('P', 'Planta')], max_length=30),
        ),
    ]
